#!/bin/sh
# File generated by ocamlbuild

cd /Users/sword/Documents/Paraverif/newParaVerifier-master/examples/test

rm -f test.dll
# Also clean the script itself
rm -f /Users/sword/Documents/Paraverif/newParaVerifier-master/examples/test/_build/sanitize.sh
